### ISSUE TITLE
wrong ccminer

### ISSUE THREAD

**Issue by angelics** [Cryptominer937/zPoolMiner#10]
from latest source.
x17 algo using wrong ccminer.
it will run ccminer tpruvot instead of palgin.
if using the latest source, i added x17 algo into ccminer_alexis78, i have to remove ccimner_palgin in order to use alexis78 mining x17.
alexis78 is the fastest for me (1050ti) using -i 20

**Comment by Cryptominer937** [comment]
Will get this patched tomorrow.

**Comment by Cryptominer937** [comment]
Testing the patch now.

**Comment by Cryptominer937** [comment]
Can you test this patch for me when you get the time to verify that it resolves the issue?
https://goo.gl/KoAuVv

**Comment by angelics** [comment]
nope. instant failed trying to benchamark only x17 for both palgin and alexis78. please add nist5 to alexis78 too. its faster

**Comment by Cryptominer937** [comment]
Very odd, copy the alexis78 miner into the x11gost folder and see what happens then, cause unless you did not try with a fresh copy if zpoolminer there should be no reason for palgin to not be being used. I am not in a rush to re-add alexis to very many things as it simply does not work on systems with more that 4 cards sue to a failing api system in the miner.

**Comment by Cryptominer937** [comment]
Ok the x11gost is a 2nd copy of alexis78 I have found the problem and will
upload the fix tomorrow. I can't just swap x17 to using Alexis as it does
not work on rigs with more than 4 cards. So I ad the ones that are optional
for Alexis to the unstable x11gost version. The problem is that the one in
the x11gost folder is broken for some reason.

**Comment by Cryptominer937** [comment]
Bin update pushed for Nvidia fixing the x17 alexis miner. to update close the miner and delete your bin folder. when you relaunch the miner it will ask to fix the missing bins so let it and the update will be done.

That should fix the issue for x17 x11gost AKA alexis not working.
