### ISSUE TITLE
Invalid costing

### ISSUE THREAD

**Issue by Eset74** [Cryptominer937/zPoolMiner#11]
Hello from Russia! Thanks for your software.

I noticed that the built-in calculator in the application gives incorrect information about the income per day. In my case, for two video cards 1070ti and 1050ti, the yield per day shows $ 14.
![zpool](https://user-images.githubusercontent.com/35626539/35182873-4edaf334-fdfe-11e7-8c04-7feb6a557bed.png)

But if you take data from the pool site, then the real figure is another day - $ 8.8.
![zpool site](https://user-images.githubusercontent.com/35626539/35182875-523cc7dc-fdfe-11e7-819e-aa0b9dedf795.png)

![3](https://user-images.githubusercontent.com/35626539/35182876-55af732e-fdfe-11e7-80ed-a518d0a903dc.png)

We take the exchange rate bitstamp ($ 12,596). Multiply this by profit (0,04697) * the number of MHs on the algorithm (15MH) = 12596 * 0.0007 = $ 8.8

Can you tell how the income per day counts in the application?

**Comment by Cryptominer937** [comment]
The miner uses a normalized profitability rate over the last 75 Min and it is calculated like this
each api value is normalizing the (current earnings +the 24 hr estimated earnings + the 24hr actual earnings)/3 = current profitability
Current profitability over the last 15 API calls is then normalized to give the best normalized factor over the last 75 Min. 
* the normailization can be edited in the configs folder inside the general.json by modifying these lines

"IQROverFactor": 3.0,
 "NormalizedProfitHistory": 15,
 "IQRNormalizeFactor": 0.0,

It is in the roadmap to add the ability to adjust these from within settings.

zpoolminer also uses the current blockchain.info pricing vs bitstamp.
