### ISSUE TITLE
request miner

### ISSUE THREAD

**Issue by angelics** [Cryptominer937/zPoolMiner#14]
hsrneoscrypt hsr

> github.com/palginpav/hsrminer/blob/master/HSR%20algo/Windows/hsrminer_hsr.exe

latest excavator 1.4 for blake2s

equihash bminer . fastest and comes with no fee switch

**Comment by Cryptominer937** [comment]
HSR is already included in 1.9.0.1 but does not work on anything except Nvidia 10XX cards.

bminer is in the plans to add.

**Comment by angelics** [comment]
hsr NEOSCRYPT is but not hsr HSR.
`https://github.com/palginpav/hsrminer`
neo and hsr in diff binary
