### ISSUE TITLE
Add new pools to your miner

### ISSUE THREAD

**Issue by rinkal26783** [Cryptominer937/zPoolMiner#20]
I like to suggest you to add these auto exchange pools to your list.
http://www.zergpool.com
http://www.hashrefinery.com/

**Comment by Cryptominer937** [comment]
Hashrefinery is planned but will look into zergpool

**Comment by Cryptominer937** [comment]
Take a look at our alpha multipool miner over in the discord current version is Pre3 this has multi pool support and more pools coming including zergpool.
 https://discord.gg/4TRKGb3
