### ISSUE TITLE
Not working with 12 GPU, works fine upto 11 GPU only

### ISSUE THREAD

**Issue by bhanvadia** [Cryptominer937/zPoolMiner#23]
zPoolMiner working good upto 11 GPUs
but when add 12 GPU to a rig, it always have error in passing command to specific miners.
And all miners show some error stating "11" GPU incorrectly specified.

**Comment by Cryptominer937** [comment]
Yes this is cause by most of the mining programs not having support for more than 11 GPU's we just have to wait for them to all have support for more cards.

**Comment by bhanvadia** [comment]
Nicehash legacy works with 12 GPUs, so yours should work too.
If i were you I would keep on legacy fork and your updates saperate, so that you are always updated along with them. And add also your changes.
Your app can be more advanced than nicehash legacy by staying ahead always.

**Comment by Cryptominer937** [comment]
our code is up to date with all the NH code but we have far more miners than there code does. some miners do not yet support more than 10 GPU's. We could remove all our more optimized miners and go backwards to were NH code is currently or we can press forward with our faster miners.

Only uggestion i have is try and split your cards across 2 instances of the mining software.
