### ISSUE TITLE
Make Benchmark Window Sizeable or Reduce It's Size

### ISSUE THREAD

**Issue by volkansen** [Cryptominer937/zPoolMiner#6]
Benchmark window is too big for a 1366x768 res screen. Had to hide the task bar to be able to click the buttons.

**Comment by Cryptominer937** [comment]
Yea i forgot to shrink it back down after adding algos to the test releases.

**Comment by Cryptominer937** [comment]
Version 1.9.0.1 has a smaller Benchmark window next release will have it so it can be resized.
