### ISSUE TITLE
More Pools

### ISSUE THREAD

**Issue by volkansen** [Cryptominer937/zPoolMiner#7]
aHashPool, HashRefinery, Yiimp.eu etc. since all of them are Yiimp based pools it shouldn't be hard zPoolMiner to support them too. Should help increase user base too.

I personally like aHashPool more as it gives me 10% - 20% more profit then Zpool. 
The name of the software "zPoolMiner" will become inappropriate but I can live with that.

**Comment by Cryptominer937** [comment]
It is in the roadmap but I am working on making the program solid first.
