### ISSUE TITLE
[INFO] [ComputeDeviceManager.Query] virtual memory size BAD

### ISSUE THREAD

**Issue by thanhvuong** [Cryptominer937/zPoolMiner#9]
Decided to try zpoolminer out on my rig. I keep getting this when I open the miner.

[INFO] [ComputeDeviceManager.Query] virtual memory size BAD

*EDIT: Also, if you leave that warning prompt open for too long, when you eventually close it, the app will hang and not finish loading.

Screenshot:
![image](https://user-images.githubusercontent.com/542038/35155118-a8723358-fcfa-11e7-8c37-519d34825969.png)

**Comment by Cryptominer937** [comment]
The general rule is to make your virtual memory match the total memory of your combined GPU's + system physical memory so seeing as you have 6 1080TI and i would guess 8GB Physical memory Virtual memory should be around 74GB in total.
